n1=eval(input("Enter First Number :"))
n2=eval(input("Enter Second number :"))

print("{} + {} = {} ".format(n1,n2,n1+n2))
print("{} - {} = {} ".format(n1,n2,n1-n2))
print("{} * {} = {} ".format(n1,n2,n1*n2))
print("{} / {} = {} ".format(n1,n2,n1/n2))
print("{} % {} = {} ".format(n1,n2,n1%n2))
print("{} // {} = {} ".format(n1,n2,n1//n2))
print("{} ** {} = {} ".format(n1,n2,n1**n2))
